name: CI
on: [push, pull_request]

permissions:
  contents: read
  pull-requests: read

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout reactea
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ">=1.18"
          check-latest: true

      - name: Build
        run: go build -v ./...

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout reactea
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ">=1.18"
          check-latest: true

      - name: Run tests
        run: go test -race -v -coverprofile=coverage.out ./...

      - name: Upload coverage
        uses: codecov/codecov-action@v3

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout reactea
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ">=1.18"
          check-latest: true

      - name: Lint
        # Its basically 3.2.0 just with schema fixes
        uses: golangci/golangci-lint-action@5acb063f68ce921cd1e8380310270f54ccbca0e4
        with:
          only-new-issues: true
