name: CI
on: [push, pull_request]

permissions:
  contents: read
  pull-requests: read

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout reactea
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ">=1.18"
          check-latest: true

      - name: Build
        run: go build -v ./...

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout reactea
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ">=1.18"
          check-latest: true

      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v3.0.0
        env:
          # Set CC_TEST_REPORTER_ID as secret of your repo
          CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
        with:
          # The report file must be there, otherwise Code Climate won't find it
          coverageCommand: go test -v -coverprofile=cover.out ./...
          coverageLocations: ${{github.workspace}}/cover.out:gocov

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout reactea
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ">=1.18"
          check-latest: true

      - name: Lint
        # Its basically 3.2.0 just with schema fixes
        uses: golangci/golangci-lint-action@5acb063f68ce921cd1e8380310270f54ccbca0e4
        with:
          only-new-issues: true
