name: lint
on: [push, pull_request]

permissions:
  contents: read
  pull-requests: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout reactea
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ">=1.18"
          check-latest: true

      - name: Lint
        # Its basically 3.2.0 just with schema fixes
        uses: golangci/golangci-lint-action@5acb063f68ce921cd1e8380310270f54ccbca0e4
        with:
          only-new-issues: true
